vignette=false
separateAo=true

sun=false
moon=false


texture.composite.colortex5=textures/distortion_maps.png
texture.composite.colortex6=textures/crosshatching_mipped.png
texture.composite.colortex7=textures/paper_texture_mipped.png
texture.composite.colortex10=textures/paper_normals_mipped.png


screen=ALBEDO_BLEND <empty> [CONTOURS] [CROSSHATCHING] [LIGHTING] 
sliders=CONTOUR_SHAKE_MAX_DISPLACEMENT CONTOUR_UB CONTOUR_CS CROSSHATCH_UB CROSSHATCH_UW CROSSHATCH_WP_THRESHOLD AMBIENT_LIGHT SHADOW_SOFTNESS SHADOW_QUALITY CONTOUR_DETECTION_KERNEL_SIZE CONTOUR_VIEW_DISTANCE CONTOUR_DISPLACEMENT_FALLOFF CONTOUR_COLOR_FALLOFF CONTOUR_THICKNESS_FALLOFF CONTOUR_NOISE CONTOUR_UW CONTOUR_WP_THRESHOLD CONTOUR_COLOR_FALLOFF_MINIMUM SUN_BRIGHTNESS MINIMUM_SKY_BRIGHTNESS ALBEDO_BLEND NORMAL_MAP_COEF CONTRAST

screen.CONTOURS=CONTOUR_DETECTION_KERNEL_SIZE CONTOUR_SHAKE_MAX_DISPLACEMENT CONTOUR_UB <empty> CONTOUR_UW CONTOUR_WP_THRESHOLD <empty> <empty> CONTOUR_VIEW_DISTANCE CONTOUR_THICKNESS_FALLOFF CONTOUR_NOISE CONTOUR_DISPLACEMENT_FALLOFF CONTOUR_COLOR_FALLOFF_MINIMUM CONTOUR_COLOR_FALLOFF
screen.CROSSHATCHING=CROSSHATCH_UB <empty> CROSSHATCH_WP_THRESHOLD CROSSHATCH_UW NORMAL_MAP_COEF
screen.LIGHTING=AMBIENT_LIGHT CONTRAST SHADOW_SOFTNESS SHADOW_QUALITY SUN_BRIGHTNESS MINIMUM_SKY_BRIGHTNESS 